### ISSUE TITLE
Error with notifications: TypeError: Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by goyerl** [chaostoolkit-incubator/chaostoolkit-aws#123]
I have HTTP Notifications configured to send Chaos Toolkit events. https://chaostoolkit.org/reference/usage/notification/#http-notification-channel

Receiving error at the end of an experiment causing the execution to exit with failure and not send notification.

I'm not sure if this issue should belong here or in chaostoolkit-lib.

Error:
```
TypeError: Object of type datetime is not JSON serializable
```

Stack:
```
[2021-10-08 18:23:41 INFO] Experiment ended with status: completed
Traceback (most recent call last):
  File "/usr/local/bin/chaos", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/chaostoolkit/cli.py", line 198, in run
    notify(settings, RunFlowEvent.RunCompleted, journal)
  File "/usr/local/lib/python3.9/site-packages/chaoslib/notification.py", line 140, in notify
    notify_with_http(channel, event_payload)
  File "/usr/local/lib/python3.9/site-packages/chaoslib/notification.py", line 165, in notify_with_http
    r = requests.post(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 471, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

Chaos Version
```
$ chaos --version
chaos, version 1.9.1
$ python --version
Python 3.9.6
$ pip list | grep -i chaos
chaostoolkit                1.9.1
chaostoolkit-aws            0.16.0
chaostoolkit-lib            1.19.0
chaostoolkit-reporting      0.13.0
```

**Comment by ciaranevans** [comment]
Closing as this is now released in version [`1.23.0` of `chaostoolkit-lib`](https://github.com/chaostoolkit/chaostoolkit-lib/blob/master/CHANGELOG.md#1230---2021-11-05)
